# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/ozon_keyword_api/v1/ozon_keyword_api.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/ozon_keyword_api/v1/ozon_keyword_api.proto',
  package='ozonmp.ozon_keyword_api.v1',
  syntax='proto3',
  serialized_options=b'ZHgithub.com/execut/ozon-keyword-api/pkg/ozon-keyword-api;ozon_keyword_api',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1ozonmp/ozon_keyword_api/v1/ozon_keyword_api.proto\x12\x1aozonmp.ozon_keyword_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"a\n\x07Keyword\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n\x03\x66oo\x18\x02 \x01(\x04R\x03\x66oo\x12\x34\n\x07\x63reated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\"B\n\x18\x44\x65scribeKeywordV1Request\x12&\n\nkeyword_id\x18\x01 \x01(\x04\x42\x07\xfa\x42\x04\x32\x02 \x00R\tkeywordId\"V\n\x19\x44\x65scribeKeywordV1Response\x12\x39\n\x05value\x18\x01 \x01(\x0b\x32#.ozonmp.ozon_keyword_api.v1.KeywordR\x05value2\xba\x01\n\x15OzonKeywordApiService\x12\xa0\x01\n\x11\x44\x65scribeKeywordV1\x12\x34.ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Request\x1a\x35.ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Response\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/ozons/{keyword_id}BJZHgithub.com/execut/ozon-keyword-api/pkg/ozon-keyword-api;ozon_keyword_apib\x06proto3'
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_KEYWORD = _descriptor.Descriptor(
  name='Keyword',
  full_name='ozonmp.ozon_keyword_api.v1.Keyword',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.ozon_keyword_api.v1.Keyword.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='foo', full_name='ozonmp.ozon_keyword_api.v1.Keyword.foo', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='foo', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created', full_name='ozonmp.ozon_keyword_api.v1.Keyword.created', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='created', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=266,
)


_DESCRIBEKEYWORDV1REQUEST = _descriptor.Descriptor(
  name='DescribeKeywordV1Request',
  full_name='ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword_id', full_name='ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Request.keyword_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\372B\0042\002 \000', json_name='keywordId', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=268,
  serialized_end=334,
)


_DESCRIBEKEYWORDV1RESPONSE = _descriptor.Descriptor(
  name='DescribeKeywordV1Response',
  full_name='ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Response.value', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='value', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=422,
)

_KEYWORD.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_DESCRIBEKEYWORDV1RESPONSE.fields_by_name['value'].message_type = _KEYWORD
DESCRIPTOR.message_types_by_name['Keyword'] = _KEYWORD
DESCRIPTOR.message_types_by_name['DescribeKeywordV1Request'] = _DESCRIBEKEYWORDV1REQUEST
DESCRIPTOR.message_types_by_name['DescribeKeywordV1Response'] = _DESCRIBEKEYWORDV1RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Keyword = _reflection.GeneratedProtocolMessageType('Keyword', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORD,
  '__module__' : 'ozonmp.ozon_keyword_api.v1.ozon_keyword_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ozon_keyword_api.v1.Keyword)
  })
_sym_db.RegisterMessage(Keyword)

DescribeKeywordV1Request = _reflection.GeneratedProtocolMessageType('DescribeKeywordV1Request', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBEKEYWORDV1REQUEST,
  '__module__' : 'ozonmp.ozon_keyword_api.v1.ozon_keyword_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Request)
  })
_sym_db.RegisterMessage(DescribeKeywordV1Request)

DescribeKeywordV1Response = _reflection.GeneratedProtocolMessageType('DescribeKeywordV1Response', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBEKEYWORDV1RESPONSE,
  '__module__' : 'ozonmp.ozon_keyword_api.v1.ozon_keyword_api_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.ozon_keyword_api.v1.DescribeKeywordV1Response)
  })
_sym_db.RegisterMessage(DescribeKeywordV1Response)


DESCRIPTOR._options = None
_DESCRIBEKEYWORDV1REQUEST.fields_by_name['keyword_id']._options = None

_OZONKEYWORDAPISERVICE = _descriptor.ServiceDescriptor(
  name='OzonKeywordApiService',
  full_name='ozonmp.ozon_keyword_api.v1.OzonKeywordApiService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=425,
  serialized_end=611,
  methods=[
  _descriptor.MethodDescriptor(
    name='DescribeKeywordV1',
    full_name='ozonmp.ozon_keyword_api.v1.OzonKeywordApiService.DescribeKeywordV1',
    index=0,
    containing_service=None,
    input_type=_DESCRIBEKEYWORDV1REQUEST,
    output_type=_DESCRIBEKEYWORDV1RESPONSE,
    serialized_options=b'\202\323\344\223\002\030\022\026/v1/ozons/{keyword_id}',
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OZONKEYWORDAPISERVICE)

DESCRIPTOR.services_by_name['OzonKeywordApiService'] = _OZONKEYWORDAPISERVICE

# @@protoc_insertion_point(module_scope)
